runtime: go123

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0
  min_idle_instances: 0

handlers:
  # Route everything through the Go application
  # The Go app will handle static serving with proper caching
  - url: /.*
    script: auto
    secure: always
