name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS
        run: git lfs checkout

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install npm
        run: npm ci

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - name: "build"
        run: "echo \"::error file=.routes/main.go,line=10,col=5::Something went wrong\" && exit 1"
