---

name: test

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Checkout LFS
        run: git lfs checkout

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "./go.mod"

      - name: Test
        uses: robherley/go-test-action@v0.1.0

      - name: Description
        uses: jadrol/pr-description-checker-action@v1.0.0
