---

runtime: go123
service: default

automatic_scaling:
  max_instances: 1
  min_instances: 0
  max_idle_instances: 0
  min_idle_instances: 0

handlers:
  - url: /image
    static_dir: .build/image
    secure: always

  - url: /(.*\.(gif|png|jpg|jpeg|ico|svg))$
    static_files: ./build/image/\1
    upload: ./build/image/.*\.(gif|png|jpg|jpeg|ico|svg)$

  - url: /index.xml
    static_files: .routes/index.xml
    upload: .routes/index.xml
    secure: always
    http_headers:
      Content-Type: application/xml; charset=utf-8

  - url: /robots.txt
    static_files: .routes/robots.txt
    upload: .routes/robots.txt
    secure: always
    http_headers:
      Content-Type: text/plain; charset=utf-8

  - url: /aphorism
    static_files: .build/aphorism.html
    upload: .build/aphorism.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /poem
    static_files: .build/poem.html
    upload: .build/poem.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /story
    static_files: .build/story.html
    upload: .build/story.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /story/the_philosophy_of_trees
    static_files: .build/the_philosophy_of_trees.html
    upload: .build/the_philosophy_of_trees.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /story/the_philosophy_of_lovers
    static_files: .build/the_philosophy_of_lovers.html
    upload: .build/the_philosophy_of_lovers.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /story/bridge
    static_files: .build/bridge.html
    upload: .build/bridge.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /story/nothing
    static_files: .build/nothing.html
    upload: .build/nothing.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review
    static_files: .build/review.html
    upload: .build/review.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/zen-and-the-art-of-motorcycle-maintenance
    static_files: .build/zen-and-the-art-of-motorcycle-maintenance.html
    upload: .build/zen-and-the-art-of-motorcycle-maintenance.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/living-on-24-hours-a-day
    static_files: .build/living-on-24-hours-a-day.html
    upload: .build/living-on-24-hours-a-day.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/howards-end
    static_files: .build/howards-end.html
    upload: .build/howards-end.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/walden
    static_files: .build/walden.html
    upload: .build/walden.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/the-history-of-modern-political-philosophy
    static_files: .build/the-history-of-modern-political-philosophy.html
    upload: .build/the-history-of-modern-political-philosophy.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /thought
    static_files: .build/thought.html
    upload: .build/thought.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /thought/responses
    static_files: .build/thought-responses.html
    upload: .build/thought-responses.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /thought/existence
    static_files: .build/thought-existence.html
    upload: .build/thought-existence.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /make
    static_files: .build/make.html
    upload: .build/make.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /grass/worker.js
    static_files: .build/grass-service-worker.js
    upload: .build/grass-service-worker.js
    secure: always
    http_headers:
      Content-Type: application/javascript

  - url: /grass
    static_files: .build/grass.html
    upload: .build/grass.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /kit
    static_files: .build/kit.html
    upload: .build/kit.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /avatar
    static_files: .build/avatar.html
    upload: .build/avatar.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /weeks-remaining
    static_files: .build/weeks-remaining.html
    upload: .build/weeks-remaining.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /word/quality
    static_files: .build/quality.html
    upload: .build/quality.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /word/equipoise
    static_files: .build/equipoise.html
    upload: .build/equipoise.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /word/flexible
    static_files: .build/flexible.html
    upload: .build/flexible.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /word
    static_files: .build/word.html
    upload: .build/word.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /nature/anolis-carolinensis
    static_files: .build/nature-anolis-carolinensis.html
    upload: .build/nature-anolis-carolinensis.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /nature
    static_files: .build/nature.html
    upload: .build/nature.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /2022/01/living-on-24-hours-a-day
    static_files: .build/living-on-24-hours-a-day.html
    upload: .build/living-on-24-hours-a-day.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /review/living-on-24-hours-a-day
    static_files: .build/living-on-24-hours-a-day.html
    upload: .build/living-on-24-hours-a-day.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /
    static_files: .build/index.html
    upload: .build/index.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8

  - url: /.*
    static_files: .build/index.html
    upload: .build/index.html
    secure: always
    http_headers:
      Content-Type: text/html; charset=utf-8
